### ISSUE TITLE
Leftover test star-free?

### ISSUE THREAD

**Issue by AmbientLighter** [mhulden/foma#110]
`test star-free` command has been removed here:

https://github.com/mhulden/foma/commit/1453a97a0f2af3244c199106a1d5f4116f9d7968#diff-7d12c3cf2f65a969472ce74412429bb9f1bb03427ca8a0db4cd9a6cd2995440dR243

but there're related references remaining 

https://github.com/mhulden/foma/blob/c9ddd88f299f3b459fae00df39cac111dc42b50e/foma/iface.c#L193

https://github.com/mhulden/foma/blob/b44022c7d9d347dc7392aabbf72c82e558767675/foma/determinize.c#L108

https://github.com/mhulden/foma/blob/b44022c7d9d347dc7392aabbf72c82e558767675/foma/foma.c#L42

@mhulden The question is: shall we restore this command or remove leftover?

**Comment by AmbientLighter** [comment]
@mhulden comments?

**Comment by mhulden** [comment]
Could be removed/cleaned-up...

**Comment by AmbientLighter** [comment]
Pull request has been submitted: https://github.com/mhulden/foma/pull/111
