### ISSUE TITLE
problem installing foma on Ubuntu 20.04.2

### ISSUE THREAD

**Issue by leoalenc** [mhulden/foma#131]
Hi! I've tried to run the pre-combiled Foma binary on my Ubuntu system, but I got the following error message:

>foma: error while loading shared libraries: libtermcap.so.2: cannot open shared object file: No such file or directory

My system doesn't have  libtermcap.so.2 in the _/lib_ directory.
I've also run the following command:

`sudo apt install foma` 

Although no error was reported, the same error message was displayed when executing the command `foma`.
Finally, I've tried to compile foma from source, running:

`sudo make; make install`

It was reported that -ltermcap was not found.
Foma is a great tool! I've used it on my mac systems as well as on older linux systems for years. So I would appreciate  any hints on how to install it on Ubuntu 20.04.2.

**Comment by AmbientLighter** [comment]
pls try to install `libncurses-dev`

**Comment by leoalenc** [comment]
> pls try to install `libncurses-dev`

@AmbientLighter, thanks! I followed your suggestion and this time I could successfully install foma from source.

**Comment by leoalenc** [comment]
Since the problem was solved, I'm closing the issue.

**Comment by leoalenc** [comment]
Since the problem was solved, I'm closing the issue.
