### ISSUE TITLE
syntax error when using non English alphabets

### ISSUE THREAD

**Issue by medaritham** [mhulden/foma#64]
Foma is giving syntax error, whenever I used ï, Ï, ñ, Ñ in the lexicon either as part of the affixes or an entry in the lexicon. I am using win32 version of Foma and notepad for the .lexc file. Thanks

**Comment by AmbientLighter** [comment]
@medaritham I think it is related to https://github.com/mhulden/foma/issues/47

**Comment by AmbientLighter** [comment]
@medaritham This issue is fixed in pull request https://github.com/mhulden/foma/pull/104/files
