### ISSUE TITLE
segmentation fault with null xducer

### ISSUE THREAD

**Issue by mcswell** [mhulden/foma#82]
`regex 0 - 0 ; !Creates xducer with 0 paths`
`eliminate flags !seg fault`

Probably not s.t. you'd do if you were manually creating code, but it can happen if the Foma code is automatically created; and I suppose it could happen under certain circumstances, should you happen to create an xducer with zero paths.  (And I'm guessing the solution is easy: if there are no paths, there's nothing to do, hence skip the flag removal code.)

**Comment by AmbientLighter** [comment]
@mcswell This issue has been fixed in pull request https://github.com/mhulden/foma/pull/102
