### ISSUE TITLE
Compilation will fail with gcc 10

### ISSUE THREAD

**Issue by scarabeusiv** [mhulden/foma#88]
Gcc 10 introduces new behavior with -fno-common and the package fails to build.

Explanation of the change can be found at our downstream bug https://bugzilla.suse.com/show_bug.cgi?id=1160244

Build log: [foma.txt](https://github.com/mhulden/foma/files/4034183/foma.txt)

**Comment by TinoDidriksen** [comment]
Debian also wants this fixed: https://bugs.debian.org/957216
