### ISSUE TITLE
yyerror() parameters and consequent syntax error prints

### ISSUE THREAD

**Issue by kryde** [mhulden/foma#97]
With current zipped master built on not particularly recent Debian i386, a syntax error on input prints apparent junk instead of the message (where I expected say "syntax error").  Sample input to provoke:

def blah 123;
regex ||;

I think regex.l defines yyerror() with 3 args (into generated lex.yy.c), but the %parse-param's in regex.y causes it to be called with 5 args (from generated regex.c).

**Comment by AmbientLighter** [comment]
@kryde This issue has been fixed in https://github.com/mhulden/foma/pull/103
